HerramientaAD/Controllers/DependeciasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using HerramientaAD.Models;
using HerramientaAD.com.Datos;
using HerramientaAD.com.Utilerias;


namespace HerramientaAD.Controllers
{
    public class DependeciasController : Controller
    {
        DependeciasModel datosDependeciasM = new DependeciasModel();
        List<ListasDesplegables> aplicacionesLista = new List<ListasDesplegables>();
        DatosDependencias datosDependeciasSQL = new DatosDependencias();
        public ActionResult Index()
        {
            if (Session["UsuarioID"] != null)
            {
                var detalleDependeciasModel = new DependeciasModel(int.Parse(Session["UsuarioID"].ToString()));
                return View(detalleDependeciasModel);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }            
        }
        public JsonResult ActualizarAplicaciones(int AreaID)
        {
            Aplicaciones aplicaciones = new Aplicaciones();

            if (aplicaciones.AplicacionesConsulta(1, AreaID, 0))
            {
                aplicacionesLista.Add(new ListasDesplegables(0, "Selecciona"));
                XmlNode xmlNode = aplicaciones.ResultadoXML.DocumentElement.SelectSingleNode("Aplicaciones");
                foreach (XmlNode elemento in xmlNode.SelectNodes("row"))
                {
                    aplicacionesLista.Add(new ListasDesplegables(
                        int.Parse(elemento.Attributes["AplicacionID"].Value.ToString()),
                        elemento.Attributes["Aplicacion"].Value.ToString())
                        );
                }
            }

            return Json(new SelectList(aplicacionesLista, "Indice", "Texto"), JsonRequestBehavior.AllowGet);
        }
        /// <summary>
        /// carga tabla
        /// </summary>
        /// <param name="appid"></param>
        /// <param name="nombre"></param>
        /// <returns></returns>
        public ActionResult ActualizaDetalle(int appid, string nombre, int Top, int Hoja)
        {
            if (Session["usuid"] != null)
            {
                DependeciasModel objdep = new DependeciasModel(appid, int.Parse(Session["usuid"].ToString()), nombre, Top, Hoja);
                return PartialView("Detalle", objdep);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        public JsonResult GeneraDiagrama(int appid, int maxe, int tipoid, string nomapp)
        {
            string diagramahtml = string.Empty;
            return Json(diagramahtml, JsonRequestBehavior.AllowGet);
        }


        public JsonResult ActualizaIndicadores(int TipoID, int AplicacionID, int ProcesoID)
        {
            var grupoDepModel = new DependeciasModel(1, TipoID, AplicacionID, ProcesoID);
            var cc = Json(grupoDepModel.Ldep, JsonRequestBehavior.AllowGet);
            return cc;
        }



        public ActionResult ActualizaTablaUsos(int AplicacionID)
        {
            datosDependeciasM.DetalleXML = TabUsodel(1, AplicacionID);
            return PartialView("Detalle", datosDependeciasM);
        }

        public XmlDocument TabUsodel(int UsuarioID, int AplicacionID)
        {
            XmlDocument detalleXML = new XmlDocument();
            if (datosDependeciasSQL.TablaUsosConsulta(UsuarioID, AplicacionID))
            {
                detalleXML = datosDependeciasSQL.ResultadoXML;
            }
            return detalleXML;
        }


        //diagrama
        public JsonResult ArregloCuadroC(int BaseDeDatosID, int Tipo)
        {
            var cc = Json("", JsonRequestBehavior.AllowGet);
            if (Session["UsuarioID"] != null)
            {
                var grupoDepModel = new DependeciasModel(int.Parse(Session["UsuarioID"].ToString()), BaseDeDatosID, Tipo);
                cc = Json(grupoDepModel.Cuadros, JsonRequestBehavior.AllowGet);
                return cc;
            }
            else
            {
                 RedirectToAction("Index", "Login");
                cc = Json("", JsonRequestBehavior.AllowGet);
            }
            return cc;
        }

        public JsonResult ArregloCuadroCN2(int Aplicacion, string NombreObj, int Top, int Hoja)
        {
            var cc = Json("", JsonRequestBehavior.AllowGet);
            if (Session["UsuarioID"] != null)
            {
                var grupoDepModel = new DependeciasModel(int.Parse(Session["UsuarioID"].ToString()), Aplicacion, NombreObj, Top, Hoja);
                cc = Json(grupoDepModel.Cuadros, JsonRequestBehavior.AllowGet);
                return cc;
            }
            else
            {
                RedirectToAction("Index", "Login");
                cc = Json("", JsonRequestBehavior.AllowGet);
            }
            return cc;            
        }

        public ActionResult ActualizaTablaUsosN2(int AplicacionID, string ObjNombre)
        {
            datosDependeciasM.DetalleXML = TabUsodelN2(1, AplicacionID, ObjNombre);
            return PartialView("Detalle", datosDependeciasM);
        }

        public XmlDocument TabUsodelN2(int UsuarioID, int AplicacionID, string ObjNombre)
        {
            XmlDocument detalleXML = new XmlDocument();
            if (datosDependeciasSQL.TablaN2Consulta(UsuarioID, AplicacionID, ObjNombre))
            {
                detalleXML = datosDependeciasSQL.ResultadoXML;
            }
            return detalleXML;
        }

    }
}

HerramientaAD/Controllers/DiagramaERController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml;

using HerramientaAD.com.Datos;
using HerramientaAD.com.Utilerias;

using HerramientaAD.Models;

namespace HerramientaAD.Controllers
{
    public class DiagramaERController : Controller
    {
        List<ListasDesplegables> aplicacionesLista = new List<ListasDesplegables>();
        List<ListasDesplegables> baseLista = new List<ListasDesplegables>();
      
        DatosDetalleTecnico datosDetalleTecnico = new DatosDetalleTecnico();
        DatosDiagramaER datosDiagramaER = new DatosDiagramaER();

        // GET: DiagramaER
        public ActionResult Index()
        {
            if (Session["UsuarioID"] != null)
            {
                var diagramaERModel = new DiagramaERModel(int.Parse(Session["UsuarioID"].ToString()));
                return View(diagramaERModel);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }




        public JsonResult ActualizarAplicaciones(int AreaID)
        {
            Aplicaciones aplicaciones = new Aplicaciones();

            if (aplicaciones.AplicacionesConsulta(1, AreaID, 0))
            {
                aplicacionesLista.Add(new ListasDesplegables(0, "Selecciona"));
                XmlNode xmlNode = aplicaciones.ResultadoXML.DocumentElement.SelectSingleNode("Aplicaciones");
                foreach (XmlNode elemento in xmlNode.SelectNodes("row"))
                {
                    aplicacionesLista.Add(new ListasDesplegables(
                        int.Parse(elemento.Attributes["AplicacionID"].Value.ToString()),
                        elemento.Attributes["Aplicacion"].Value.ToString())
                        );
                }
            }

            return Json(new SelectList(aplicacionesLista, "Indice", "Texto"), JsonRequestBehavior.AllowGet);
        }

        public JsonResult ActualizarBase(string Filtro, string Tipo, int AplicacionID)
        {
            if (AplicacionID > 0)
            {
                if (datosDetalleTecnico.ObtenFiltros(Filtro, Tipo, AplicacionID, string.Empty, string.Empty, string.Empty))
                {
                    baseLista.Add(new ListasDesplegables(0, "Selecciona"));
                    XmlNode xmlNode = datosDetalleTecnico.ResultadoXML.DocumentElement.SelectSingleNode("Filtros");
                    foreach (XmlNode elemento in xmlNode.SelectNodes("row"))
                    {
                        baseLista.Add(new ListasDesplegables(
                            int.Parse(elemento.Attributes["Numero"].Value.ToString()),
                            elemento.Attributes["Nombre"].Value.ToString())
                            );
                    }
                }
            }

            return Json(new SelectList(baseLista, "Indice", "Texto"), JsonRequestBehavior.AllowGet);
        }

    
    

        public ActionResult ActualizarDiagrama(int BaseDeDatosID, DiagramaERModel diagramaERModel, string Tabla)
        {
            if (Session["UsuarioID"] != null)
            {
                diagramaERModel.ResultadoXML = ObtenerDatos(1, int.Parse(Session["UsuarioID"].ToString()), BaseDeDatosID, Tabla);
                XmlNode xmlNode = datosDiagramaER.ResultadoXML.DocumentElement.SelectSingleNode("DatosBD");
                foreach (XmlNode elemento in xmlNode.SelectNodes("row"))
                {
                    diagramaERModel.Cuadros.Add(new ElementosDiagramaER.Cuadros(
                        int.Parse(elemento.Attributes["Numero"].Value.ToString()),
                        elemento.Attributes["Tabla"].Value.ToString())
                        );
                }

                diagramaERModel.ResultadoXML = ObtenerDatos(2, int.Parse(Session["UsuarioID"].ToString()), BaseDeDatosID, Tabla);
                xmlNode = datosDiagramaER.ResultadoXML.DocumentElement.SelectSingleNode("DatosBD");
                foreach (XmlNode elemento in xmlNode.SelectNodes("row"))
                {
                    diagramaERModel.Relaciones.Add(new ElementosDiagramaER.Relaciones(
                        int.Parse(elemento.Attributes["From"].Value.ToString()),
                        int.Parse(elemento.Attributes["To"].Value.ToString()),
                        elemento.Attributes["Text"].Value.ToString())
                        );
                }

                return View("Index", diagramaERModel);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        public XmlDocument ObtenerDatos(int Tipo, int UsuarioID, int BaseDeDatosID, string Tabla)
        {
            XmlDocument detalleXML = new XmlDocument();
            if (datosDiagramaER.DiagramaERConsulta(Tipo, UsuarioID, BaseDeDatosID, Tabla))
            {
                detalleXML = datosDiagramaER.ResultadoXML;
            }
            return detalleXML;
        }


        //MMOB


        public JsonResult ArregloCuadroC(int BaseDeDatosID, int Tipo, string Tabla)
        {
            var accion = (Tipo == 3 || Tipo == 1) ? 1 : 2;
            var cc = Json("", JsonRequestBehavior.AllowGet);
            if (Session["UsuarioID"] != null)
            {
                var grupoDepModel = new DiagramaERModel(int.Parse(Session["UsuarioID"].ToString()), BaseDeDatosID, accion, Tabla, Tipo);
                if (Tipo == 1)
                {
                    cc = Json(grupoDepModel.Cuadros, JsonRequestBehavior.AllowGet);
                }
                else if (Tipo == 2)
                {
                    cc = Json(grupoDepModel.Relaciones, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    cc = Json(grupoDepModel.TablaLista, JsonRequestBehavior.AllowGet);

                   
                }
            }
            else
            {
                RedirectToAction("Index", "Login");
            }
            return cc;
        }
    }
}

HerramientaAD/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml;

using HerramientaAD.Models;
using HerramientaAD.com.Datos;

namespace HerramientaAD.Controllers
{
    public class LoginController : Controller
    {
        LoginModel loginModel = new LoginModel();
        Usuarios usuarios = new Usuarios();

        // GET: Login
        public ActionResult Index()
        {
            Session["UsuarioID"] = null;
            Session["usuid"] = null;
            return View();
        }

        public ActionResult Ingresar(LoginModel loginModel)
        {
            if (!ModelState.IsValid)
            {
                return View("Index", loginModel);
            }

            if (usuarios.UsuariosValida(loginModel.Usuario, loginModel.Contraseña))
            {
                XmlNode xmlNode = usuarios.ResultadoXML.DocumentElement.SelectSingleNode("Usuario");
                XmlNode datosUsuario = xmlNode.ChildNodes[0];

                Session["UsuarioID"] = datosUsuario.Attributes["UsuarioID"].Value.ToString();
                Session["UsuarioNombre"] = datosUsuario.Attributes["Nombre"].Value.ToString() + " " + 
                                           datosUsuario.Attributes["Apellido_Paterno"].Value.ToString() + " " + 
                                           datosUsuario.Attributes["Apellido_Materno"].Value.ToString();

                
                return RedirectToAction("Index", "Tableros");
            }

            ViewBag.Message = "Usuario no Registrado";
            return View("Index", loginModel);
        }
    }
}

HerramientaAD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <link href="~/Content/jquery-ui-1.10.4.css" rel="stylesheet" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title </title>
    <link rel="shortcut icon" href="~/Images/logo_login.png">

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <script>
        function openNav() {
            document.getElementById("sidebar-menu").style.display = 'block'
        }
        function closeNav() {
            document.getElementById("sidebar-menu").style.display = 'none'
        }
    </script>
    <style>


    </style>
</head>
<body>
    <div class="fixed-top">
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary  border-bottom border-white">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="navbar-brand" href="@Url.Action("Index", "Tableros")">Tablero General</a>
                    </li>
                    <li class="nav-item">
                        <a class="navbar-brand" href="@Url.Action("Index", "DetalleTecnico")">Detalle Técnico</a>
                    </li>
                    @*<li class="nav-item">
                        <a class="navbar-brand" href="@Url.Action("Index", "DiagramaER",new {BaseDeDatosID = 1})">Diagrama E-R</a>
                    </li>*@
                    <li class="nav-item">
                        <a class="navbar-brand" href="@Url.Action("Index", "Dependecias")">Dependencias</a>
                    </li>
                    @*<li class="nav-item">
                        <a class="navbar-brand" href="@Url.Action("Metricas", "Tableros")">Métricas</a>
                    </li>*@
                    @*<li class="nav-item">
                        <a class="navbar-brand" href="/Procesos/index.html" target="_blank" >Procesos</a>
                    </li>*@
                    @if (ViewBag.Aplicacion > 0)
                    {
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="true" onclick="openNav()">Ver  @ViewBag.NombreAplicacion</a>
                            <div id="sidebar-menu" onmouseleave="closeNav()" class="dropdown-menu show" x-placement="bottom-start" style="display:none; position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(0px, 38px, 0px);">
                                <a class="dropdown-item" href="@Url.Action("Inicial", "Tableros", new { AplicacionID = ViewBag.Aplicacion } )">Tablero  @ViewBag.NombreAplicacion</a>
                                <div class="dropdown-divider"></div>
                                @*<a class="dropdown-item" href="@Url.Action("AnalisisBD", "Tableros", new { AplicacionID = ViewBag.Aplicacion })">Estadísticas de Base de Datos</a>*@
                                <a class="dropdown-item" href="@Url.Action("AnalisisCM", "Tableros", new { AplicacionID = ViewBag.Aplicacion })">Diagrama de Clases, Funciones y Métodos</a>
                                <div class="dropdown-divider"></div>
                                @*<a class="dropdown-item" href="@Url.Action("GrupoBD", "Tableros", new { AplicacionID = ViewBag.Aplicacion })">Objetos de Base de Datos</a>*@
                                <a class="dropdown-item" href="@Url.Action("GrupoCM", "Tableros", new { AplicacionID = ViewBag.Aplicacion })">Objetos de Clases, Funciones y Métodos</a>
                                <a class="dropdown-item" href="@Url.Action("GrupoWS", "Tableros", new { AplicacionID = ViewBag.Aplicacion })">Objetos de Servicios e Interfaces</a>
                                @*<div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="@Url.Action("ResumenHallazgos", "Tableros", new { AplicacionID = ViewBag.Aplicacion, BaseDeDatosID = 0 })">Resumen de hallazgos</a>*@

                            </div>
                        </li>
                    }
                </ul>
            </div>
            <form class="form-inline my-2 my-lg-0">
                <a class="navbar-brand my-2 my-sm-0" href="@Url.Action("Index", "Login")">Salir</a>
            </form>
        </nav>
        
    </div>


    <br />
    <br />
    <br />  
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; Visor de resultados del Anális de Dependencias</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>



</html>